-- Create the products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  image_url TEXT,
  description TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to view products (Public Read)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow public read access'
    ) THEN
        CREATE POLICY "Allow public read access" ON products FOR SELECT USING (true);
    END IF;
END $$;

-- Create a policy to allow authenticated users to insert (Optional, mainly for admin)
-- For now, we assume you are running this SQL in the editor which bypasses RLS.

-- Insert the product data from PopularFoods.jsx
INSERT INTO products (id, name, price, category, rating, image_url, description) VALUES
(1, 'Spicy Burger', 8.50, 'Burger', 5, '/food-burger.png', 'A delicious spicy burger with fresh ingredients.'),
(2, 'French Fry', 5.50, 'French Fry', 4, '/food-fries.png', 'Crispy and golden french fries.'),
(3, 'Italian Pasta', 10.50, 'Pasta', 5, '/food-pasta.png', 'Authentic Italian pasta with rich sauce.'),
(4, 'Club Sandwich', 6.50, 'Sandwich', 5, '/food-sandwich.png', 'Classic club sandwich with multiple layers.'),
(5, 'Cold Drink', 2.50, 'Cold Drinks', 4, '/food-coke.png', 'Refreshing cold drink to accompany your meal.'),
(6, 'Combo Pack', 15.50, 'Combo', 5, '/food-combo.png', 'Complete meal combo pack for great value.'),
(7, 'Double Cheese Burger', 11.50, 'Burger', 5, '/hero-burger.png', 'Double the cheese, double the taste.'),
(8, 'Crispy Chicken Burger', 9.50, 'Burger', 5, '/offer-burger.png', 'Crunchy crispy chicken burger.'),
(9, 'Creamy Alfredo', 12.50, 'Pasta', 5, '/offer-pasta.png', 'Rich and creamy Alfredo pasta.'),
(10, 'Mega Family Combo', 19.50, 'Combo', 5, '/offer-combo.png', 'Mega combo pack suitable for the whole family.')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  description = EXCLUDED.description;
